name: Generate Snake
permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at 00:00 UTC
  workflow_dispatch:       # lets you run it manually
  push:
    branches: ["main"]     # change to "master" if your default branch is master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: SANDUN55
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
